<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
/** @var \Magefan\GoogleTagManager\Block\Adminhtml\System\Config\Form\Button $block */
/** @var \Magento\Framework\Escaper $escaper */
// phpcs:ignoreFile
?>
<?php
if (!isset($escaper)) {
    /* Compatability fix for old Magento versions */
    $escaper = $block;
}
?>
<div class="pp-buttons-container">
    <?php if ($block->getRequest()->getParam('website')) { ?>
        <strong>
            <?= $escaper->escapeHtml(__('Container generation is not available for website scope.')) ?>
        </strong>
    <?php } else { ?>
        <button type="button" id="mf_download">
            <?= $escaper->escapeHtml(__('Generate JSON Container & Download File')); ?>
        </button>
        <p>
            <br/>
            <?= __('Once the JSON file is downloaded, upload it to %1 > Choose Container > Admin > Import Container.', '<a href="https://tagmanager.google.com/" title="Google Tag Manager" target="_blank">Google Tag Manager</a>') ?>
        </p>
        <script>
            require([
                'jquery',
                'domReady!'
            ], function ($) {
                $('#mf_download').on('click', function(event) {
                    event.preventDefault;
                    window.location='<?= $escaper->escapeUrl(
                        $block->getUrl(
                            'mfgoogletagmanager/container/generate',
                            ['store_id' => (int)$block->getRequest()->getParam('store') ?: null]
                        )
                    )?>';
                });
            });
        </script>
    <?php } ?>
</div>

